// ── Apples to Apples — Card Data ────────────────────────────────────────────

const GREEN_CARDS = [
  // Classic adjectives
  'Terrifying', 'Overrated', 'Adorable', 'Awkward', 'Legendary',
  'Suspicious', 'Unforgettable', 'Ridiculous', 'Wholesome', 'Chaotic',
  'Majestic', 'Cringeworthy', 'Inspiring', 'Disgusting', 'Heroic',
  'Hilarious', 'Romantic', 'Dangerous', 'Underrated', 'Magical',
  'Annoying', 'Satisfying', 'Confusing', 'Beautiful', 'Heartbreaking',
  'Mesmerizing', 'Dramatic', 'Rebellious', 'Shocking', 'Cozy',
  'Haunting', 'Powerful', 'Useless', 'Delightful', 'Toxic',
  'Mysterious', 'Refreshing', 'Painful', 'Genius', 'Pathetic',
  'Epic', 'Gentle', 'Wild', 'Boring', 'Spicy',
  'Creepy', 'Elegant', 'Furious', 'Peaceful', 'Intense',
  'Foolish', 'Glorious', 'Clumsy', 'Brave', 'Bizarre',
  'Sensational', 'Greedy', 'Lazy', 'Fearless', 'Petty',
  'Sassy', 'Gloomy', 'Brilliant', 'Reckless', 'Charming',

  // Modern / meme-friendly prompts
  'Main Character Energy', 'Worst Superpower', 'Peak Comedy',
  'Red Flag', 'Green Flag', 'Certified Classic', 'Extremely Cursed',
  'Surprisingly Deep', 'Oddly Comforting', 'Criminally Underrated',
  'Would Go Viral', 'Core Memory', 'Fever Dream', 'Gut-Wrenching',
  'Chef\'s Kiss', 'Nightmare Fuel', 'Top Tier', 'Bottom Tier',
  'Unhinged', 'Based', 'Totally Overrated', 'Secretly Evil',
  'Chaotic Good', 'Lowkey Genius', 'Highkey Annoying',
  'Unexpectedly Wholesome', 'So Bad It\'s Good', 'Life-Changing',
  'Mildly Infuriating', 'Strangely Addictive', 'Weirdly Attractive',
  'Perfectly Timed', 'Completely Unhinged', 'Suspiciously Specific',
  'Aggressively Average', 'Emotionally Devastating', 'Chaotic Neutral',
  'Unreasonably Expensive', 'Surprisingly Violent', 'Effortlessly Cool',
  'Dangerously Fun', 'Deeply Unsettling', 'Absurdly Cute',
  'Irrationally Angry', 'Criminally Overlooked', 'Objectively Wrong',
  'Universally Beloved', 'Quietly Powerful', 'Instantly Regrettable',
  'Aggressively Wholesome', 'Painfully Relatable', 'Absolutely Iconic',

  // Question-style prompts
  'Most Likely to Trend', 'Least Likely to Survive a Horror Movie',
  'Most Likely at 3 AM', 'Best First Date Activity',
  'Worst Gift for Your Boss', 'Best Thing to Yell in Public',
  'Most Florida Thing', 'Worst Thing to Google at Work',
  'Best Conversation Starter', 'Most Likely to Start a Cult',
  'Least Impressive Talent', 'Best Band Name',
  'Most Chaotic Pet', 'Worst Alarm Sound',
  'Best Thing About Being an Adult', 'Most Dramatic Exit',
  'Worst Thing to Say at a Wedding', 'Best Kept Secret',
  'Most Likely to Be a Villain Origin Story',
  'Worst Thing to Find Under Your Bed',
  'Best Thing to Bring to a Deserted Island',
  'Most Likely to Cause an International Incident',
  'Worst Password', 'Best Plot Twist',
  'Most Likely to Be Haunted', 'Worst Life Advice',
  'Best Thing to Name a Boat', 'Most Suspicious Search History',
  'Worst Thing to Whisper to a Stranger',
  'Best Use of Duct Tape', 'Most Dramatic Overreaction',
];

const RED_CARDS = [
  // Everyday life
  'Stepping on a Lego', 'Your Browser History', 'Gas Station Sushi',
  'The Person Who Claps When the Plane Lands', 'Accidentally Liking a 3-Year-Old Photo',
  'Forgetting Someone\'s Name Mid-Conversation', 'Eating Cereal at Midnight',
  'Reply-All to the Entire Company', 'Pretending to Laugh at a Joke You Don\'t Get',
  'The Snooze Button', 'Parallel Parking', 'Getting the WiFi Password',
  'A Grocery Store on Sunday', 'Waving Back at Someone Who Wasn\'t Waving at You',
  'The Last Slice of Pizza', 'Autocorrect', 'Reading Terms and Conditions',
  'Your Phone at 1% Battery', 'A Cold Toilet Seat', 'Losing One Sock in the Dryer',
  'Accidentally Calling Your Teacher "Mom"', 'Walking into a Glass Door',
  'The DMV', 'Forgetting Why You Walked into a Room',
  'A Shopping Cart with One Bad Wheel', 'That Weird Noise Your Car Makes',
  'Wet Socks', 'The Middle Seat on a Plane', 'Tangled Earbuds',
  'A Microwave That Beeps Too Loud', 'Setting 47 Alarms to Wake Up',
  'When the Store Is Out of Your Favorite Snack', 'The Group Project Partner Who Does Nothing',
  'Accidentally Sending a Text to the Wrong Person', 'Trying to Find Parking',

  // People & characters
  'Your Weird Uncle at Thanksgiving', 'That One Neighbor',
  'A Florida Man', 'The IT Guy', 'Someone\'s Grandma on Facebook',
  'A Toddler with a Permanent Marker', 'A Cat Knocking Things Off Tables',
  'A Seagull at the Beach', 'That Kid Who Reminds the Teacher About Homework',
  'Your Future Self', 'A Mall Santa', 'A Very Confident Wrong Person',
  'The Person Microwaving Fish at Work', 'A Pigeon in a Train Station',
  'A Dog Wearing Sunglasses', 'Someone Who Peaked in High School',
  'The Neighborhood Gossip', 'A Surprisingly Jacked Librarian',
  'The Person Who Brings a Guitar to Every Party',
  'Your Mom\'s Friend\'s Son Who\'s "Doing So Well"',
  'A Raccoon in a Dumpster', 'The Person Reading Over Your Shoulder Right Now',
  'A Motivational Speaker at 7 AM', 'That One Substitute Teacher',
  'A Very Dramatic Toddler', 'The HOA President',
  'An Overly Enthusiastic Tour Guide', 'A Passive-Aggressive Coworker',

  // Food & drink
  'Pineapple on Pizza', 'Black Licorice', 'Gas Station Coffee',
  'A Suspiciously Cheap Buffet', 'Warm Lemonade',
  'Leftovers You\'re Not Sure About', 'An Energy Drink at 11 PM',
  'A Soggy Sandwich', 'Free Samples at Costco', 'Burnt Popcorn',
  'A Smoothie That\'s Just Kale', 'Cereal with Water',
  'Gas Station Egg Salad', 'Mystery Flavor Jelly Beans',
  'A Birthday Cake from the Grocery Store', 'Airport Food Prices',
  'Candy Corn', 'Cold French Fries', 'Instant Ramen at 2 AM',
  'A Casserole from the 1970s', 'Unripe Avocado', 'Oat Milk',

  // Technology
  'Your WiFi Going Out During a Movie', 'Robot Vacuum That Gets Stuck',
  'Autocorrect Changing "Duck"', 'A Printer That Only Works Sometimes',
  'Accidentally Going Live on Social Media', 'CAPTCHA Tests',
  'Software Updates at the Worst Time', 'A Smart Fridge',
  'Your Mom Discovering Emojis', 'A 45-Minute YouTube Tutorial for a 2-Minute Task',
  'Accidentally Opening the Front Camera', 'The "K" Text',
  'A Robot That Can Dance', 'AI-Generated Art', 'Typing "…" Then Never Sending',
  'Someone\'s Expired Antivirus Software', 'Comic Sans',
  'The Spinning Loading Wheel', 'Pop-Up Ads', 'The Blue Screen of Death',
  'Your Mom\'s iPad With 200 Tabs Open', 'A Password You Forgot',

  // Places & events
  'IKEA on a Saturday', 'A Haunted House (the Fun Kind)',
  'Black Friday at Walmart', 'The Bermuda Triangle',
  'A Wedding Where Someone Objects', 'The Waiting Room at the Dentist',
  'Area 51', 'A Middle School Dance', 'The Mariana Trench',
  'A Very Long Elevator Ride with a Stranger', 'A Public Restroom',
  'An Escape Room Where No One Agrees', 'The Twilight Zone',
  'A Costco Parking Lot', 'Disney World in August',
  'A Zoom Meeting That Could\'ve Been an Email', 'The DMV at 4:55 PM',
  'An All-You-Can-Eat Buffet', 'The Backstage of a School Play',
  'The "Employees Only" Room', 'A Haunted Airbnb',

  // Abstract concepts & feelings
  'Imposter Syndrome', 'That Feeling Before a Road Trip',
  'The Sunday Scaries', 'Main Character Syndrome', 'Deja Vu',
  'The Urge to Press a Big Red Button', 'Second-Hand Embarrassment',
  'Buyer\'s Remorse', 'FOMO', 'The 3 PM Slump',
  'Existential Dread at a Birthday Party', 'Post-Vacation Depression',
  'The Confidence of a Mediocre Man', 'Spite', 'Chaotic Neutral Energy',
  'Unearned Confidence', 'Productive Procrastination',
  'The Vibe Shift', 'Nostalgia for Something That Never Happened',
  'Decision Fatigue at a Restaurant', 'The Ick',
  'Accidentally Manifesting Something Bad', 'Toxic Positivity',

  // Activities & situations
  'Building IKEA Furniture Without Instructions',
  'Teaching Your Parents to Use Technology',
  'Trying to Fold a Fitted Sheet', 'Running to Catch a Bus',
  'Explaining a Meme to Your Parents', 'Karaoke Night',
  'Doing Taxes', 'Assembling a Gingerbread House',
  'A PowerPoint Presentation with Too Many Animations',
  'Trying to Take a Group Photo', 'A Trust Fall Gone Wrong',
  'Whispering the Wrong Answer Loudly', 'Speed Dating',
  'Accidentally Joining a Conga Line', 'A Three-Hour Meeting',
  'Trying to Catch a Fly with Chopsticks', 'A Silent Elevator Ride',
  'Explaining Your Job to Your Grandparents',
  'Trying to Open a Jar', 'Walking into a Spider Web',
  'A Fire Drill During Lunch', 'Learning to Ride a Unicycle',

  // Pop culture & media
  'A Movie Sequel Nobody Asked For', 'The Disney Vault',
  'A Reboot of a Beloved Childhood Show', 'The Post-Credits Scene',
  'A Very Specific Spotify Playlist', 'A True Crime Podcast',
  'The "Based on a True Story" Disclaimer', 'A One-Hit Wonder',
  'The Training Montage', 'The Wilhelm Scream',
  'A Very Dramatic Soap Opera', 'Background Actors in Movies',
  'The Movie They Show on Airplanes', 'A Laugh Track',
  'A Clickbait Article', 'The Comments Section',
  'A Meme That Won\'t Die', 'Reality TV Drama', 'Elevator Music',
  'An Unpopular Opinion That\'s Actually Right',

  // Animals
  'A Goose with an Attitude', 'A Cat Ignoring You on Purpose',
  'An Overly Friendly Golden Retriever', 'A Parrot That Swears',
  'Raccoons That Open Trash Cans', 'A Duck in a Business Suit',
  'A Squirrel with Trust Issues', 'A Penguin Sliding on Ice',
  'A Very Judgmental Cat', 'Pigeons at a Café',
  'A Spider in the Shower', 'A Dog That Steals Socks',
  'Bees', 'A Hamster on a Wheel', 'A Crow That Holds Grudges',
  'An Emotional Support Alligator', 'A Deer in Headlights',
  'A Chihuahua That Thinks It\'s a Great Dane',

  // Misc modern / Gen Z
  'Unread Notifications', 'Crop Tops in Winter',
  'An Influencer at Brunch', 'The "No Worries If Not" Text',
  'A Participation Trophy', 'Astrology as a Personality',
  'Your Spotify Wrapped', 'A Very Long Voicemail',
  'The Read Receipt', 'Quiet Quitting',
  'A Resume Written in Crayon', 'Ghosting', 'Doom Scrolling at 3 AM',
  'A Hot Take That Ages Poorly', 'Manifesting', 'The Algorithm',
  'A Niche Hobby Nobody Understands', 'Posting "Living My Best Life"',
  'Unprompted Life Advice from Strangers', 'The Talking Phase',
  'Passive-Aggressive Post-It Notes', 'A Playlist Title That\'s Way Too Personal',
  'Being "Literally Dead" (Figuratively)',

  // Random wild cards
  'A Conspiracy Theory That Turned Out True', 'A Very Tiny Horse',
  'The Number 7', 'Velcro', 'A Fortune Cookie That\'s Weirdly Accurate',
  'Bubblewrap', 'A Potato', 'Quicksand (In Movies vs. Real Life)',
  'The Sound of Dial-Up Internet', 'A Kazoo',
  'The Oxford Comma', 'Banana Peels', 'Invisible Ink',
  'A Plot Hole You Can\'t Unsee', 'The Edge of the Map in a Video Game',
  'A Suspiciously Perfect Circle', 'The Sock Behind the Dryer',
  'Déjà Vu About Déjà Vu', 'A Strongly Worded Letter',
  'The "I\'m Not Mad, Just Disappointed" Face',
  'A Compliment That\'s Actually an Insult',
  'The Untouched Gym Membership', 'A Perfectly Timed Photo Bomb',
  'Accidentally Making Eye Contact with a Stranger',
  'The Junk Drawer Everyone Has', 'A Weirdly Motivational Fortune Cookie',
  'The Last Piece of a Puzzle', 'A Mysterious Key That Fits Nothing',
  'The Dramatic Chipmunk', 'An Unexplained Bruise',
  'Someone Eating Loudly', 'The Backup Dancer Energy',
  'The Confident Walk After Getting a Haircut',
  'An Uncomfortable Amount of Eye Contact',
  'The Song That Gets Stuck in Everyone\'s Head',

  // Extra fillers for variety
  'A Secret Handshake', 'The Wrong Kind of Cheese',
  'A Coupon That Just Expired', 'A Very Specific Fear',
  'The Smell of a New Car', 'A Handshake That Lasts Too Long',
  'Someone Coughing During the Quiet Part', 'A Candle That Smells Like Nothing',
  'The "Let Me Speak to the Manager" Haircut',
  'A Surprisingly Good Airport Nap', 'The Elevator That Stops at Every Floor',
  'A Very Long Grocery List', 'Someone Who Always One-Ups Your Story',
  'The Person Who Says "Actually…"', 'An Awkward Silence',
  'A Thumb War', 'Your Search History from 2012',
  'The Wrong Turn on a Road Trip', 'A Very Enthusiastic High Five',
  'The Feeling of Stepping on Something Wet in Socks',
  'A Pun That\'s So Bad It\'s Good', 'The "New Year, New Me" Post',
  'A Blanket That\'s Too Short', 'The "Are We There Yet?" Phase',
  'A Very Confident Typo', 'The Last French Fry',
  'A Regrettable Haircut from the 2000s', 'Holding in a Sneeze',
  'The Satisfaction of Peeling Off Screen Protector Plastic',
  'A Compliment from a Stranger', 'Walking in on the Wrong Meeting',
  'The Friend Who Always Says "We Should Hang Out" But Never Does',

  // School & work
  'A Pop Quiz on a Monday', 'The Office Coffee Machine',
  'Accidentally Unmuting Yourself', 'A Networking Event with Bad Appetizers',
  'The Company Retreat', 'An Email That Says "Per My Last Email"',
  'A Coworker\'s Desktop Wallpaper', 'The Printer Jamming Before a Deadline',
  'Casual Friday Taken Too Far', 'A Mandatory Fun Activity',
  'The Teacher\'s Pet', 'Getting Picked Last in Gym Class',
  'A College All-Nighter', 'A Motivational Poster in a Cubicle',
  'A Study Group That Doesn\'t Study', 'The School Lunch Mystery Meat',
  'The First Day at a New Job', 'A LinkedIn Humble Brag',
  'An Out-of-Office Reply from 2019', 'A Conference Call Nobody Wanted',

  // Travel & adventure
  'A Layover in a City You Can\'t Pronounce', 'Jet Lag',
  'A Map That\'s Definitely Wrong', 'A Road Trip with No Snacks',
  'The Hotel Breakfast Buffet', 'A Tourist Taking Selfies Everywhere',
  'A Flight Delayed 6 Hours', 'Lost Luggage',
  'A Hostel with Questionable Reviews', 'The Window Seat vs. Aisle Seat Debate',
  'A Souvenir Nobody Wants', 'The "We\'ll Never Speak of This" Vacation Moment',
  'A Campfire That Won\'t Light', 'Sleeping in a Tent During a Storm',
  'The Wrong Exit on the Highway', 'A Hotel Room Key That Never Works',

  // Sports & competition
  'A Participation Trophy', 'A Referee\'s Bad Call',
  'The Wave in a Stadium', 'An Overly Competitive Board Game Night',
  'A Hole-in-One by Accident', 'The Person Who Takes Mini Golf Too Seriously',
  'A Victory Dance', 'Trash Talk from a Five-Year-Old',
  'A Sore Loser', 'An Underdog Comeback Story',
  'A Mascot with a Questionable Costume', 'Fantasy Football Drama',
  'The Half-Time Show', 'A Very Dramatic Foul',

  // Holidays & celebrations
  'A Thanksgiving Food Coma', 'The Awkward Family Photo',
  'A White Elephant Gift Exchange', 'Secret Santa Stress',
  'A New Year\'s Resolution That Lasts One Day', 'A Birthday Song at a Restaurant',
  'A Fourth of July Firework Fail', 'Valentine\'s Day for Singles',
  'A Halloween Costume Nobody Gets', 'The Holiday Newsletter',
  'Black Friday at 4 AM', 'The Relative Who Falls Asleep After Dinner',
  'A Gingerbread House Disaster', 'Wrapping a Gift You\'re Bad at Wrapping',

  // Health & fitness
  'Leg Day', 'A Gym Selfie', 'A Smoothie That Costs $14',
  'A Fitness Tracker Judging You', 'A Yoga Pose You Can\'t Do',
  'A Cold That Won\'t Go Away', 'Waking Up Before Your Alarm',
  'The Hiccups at the Worst Time', 'A Sneeze That Won\'t Come',
  'A Very Enthusiastic Gym Bro', 'Running for the Bus',
  'A DIY Haircut', 'Sleeping Wrong on Your Neck',

  // Nature
  'A Sunset Nobody Photographed Well', 'Mosquitoes',
  'Stepping in a Puddle', 'A Rainbow After a Storm',
  'Sand in Your Shoes', 'A Snowflake Landing on Your Nose',
  'The Last Day of Summer', 'A Very Determined Ant',
  'A Tree That Looks Like Something Else', 'Thunder at 3 AM',
  'A Flower Growing Through Concrete', 'A Sunset That Looks Fake',
];

module.exports = { GREEN_CARDS, RED_CARDS };
